name: Faça uma requisição no Render a cada 14 minutos

on:
  schedule:
    - cron: "*/14 * * * *"

jobs:
  render-request:
    runs-on: ubuntu-latest
    steps:
      - name: Get Products
        run: curl https://medusa-server-s9pw.onrender.com/store/products